### ISSUE TITLE
Trying to run Python code, but got 'object has no attribute' error

### ISSUE THREAD

**Issue by mattiav34** [regina-normal/regina#69] opened 2021-04-16 13:09 UTC
I am trying to run the example reported here:
https://arxiv.org/abs/1208.2504
but I keep getting the error: AttributeError: 'regina.engine.Triangulation3' object has no attribute 'getNumberOfVertices'
here is my script:
>>> f=open('output.txt','r')
>>> sig=f.readline()
>>> while sig:
...  tri=NTriangulation.fromIsoSig(sig)
...  if tri.getNumberOfVertices() == 2:
...   if tri.isThreeSphere():
...    print(sig)
...  sig=f.readline()

Also where do I find a list of the command I can use in a Python script with their description?

**Comment by baburton** [comment] 2021-04-16 13:51
Hi - the programmers’ interface has had an overhaul since 2012. It should work if you change getNumberOfVertices() to countVertices(); also you should change NTriangulation to Triangulation3 (since the old NTriangulation alias will disappear in the next version of regina).

For a summary of how the programmers’ interface has changed, see:
https://regina-normal.github.io/regina4to5.html
https://regina-normal.github.io/regina5to6.html

For a list of commands, it’s a bit messier since (1) Regina is really written in C++, and the python classes are just interfaces to the real C++ code; and (2) the C++ code is very well documented in the headers but the automated C++-to-HTML documentation tool struggles a bit to understand the C++ templates. Having said that: the HTML documentation for the C++ code is online, and it does include notes on when/how the python interface differs.

https://regina-normal.github.io/engine-docs/index.html

If you’re not sure how to do something, you are welcome to ask here.

Best regards - Ben.

**Comment by baburton** [comment] 2022-09-29 13:33
Closing this now, since it's not a bug.

The instructions for updating your code are now online at: https://regina-normal.github.io/api/recent.html.

- Ben.

**Closed by baburton** 2022-09-29 13:33 UTC
