### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by beew** [regina-normal/regina#72] opened 2021-06-30 11:06 UTC
Tried to build regina 6.0.1 from source and make failed with
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_core.so: undefined reference to `__log10_finite'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_core.so: undefined reference to `__exp_finite'
collect2: error: ld returned 1 exit status
make[2]: *** [qtui/src/CMakeFiles/regina-gui.dir/build.make:1878: qtui/src/regina-gui] Error 1
make[1]: *** [CMakeFiles/Makefile2:2477: qtui/src/CMakeFiles/regina-gui.dir/all] Error 2
```

OS is Ubuntu 20.04.  Thanks.

**Comment by WPettersson** [comment] 2021-06-30 11:32
Closing as duplicate of #70, please see that issue which has fixes and upstream bug reports.

**Closed by WPettersson** 2021-06-30 11:32 UTC
